In [ ]:
# machine learning ->
# data(50) ---> x(input data), y(target data)
# x---> x_train , x_test
# y ---> y_train , y_test
# for machine learning training we pass x_train and y_train
# for ml testing -> (x_test) ---> y_pred

1+1 =2
1+2=3
1+4=5

x = (1+1 ,1+2 ,1+4)
y  = 2,3,5
x_train=(1+1,1+2)
x_test = (1+4)
y_train = (2,3)
y_test=(5)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/covid_toy - covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df.shape

(100, 6)

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.drop(columns= ['city'])

In [ ]:
df['gender'] =df['gender'].map({'Female':1,'Male':0 })

In [ ]:
df.head()

   age  gender  fever cough has_covid
0   60       0  103.0  Mild        No
1   27       0  100.0  Mild       Yes
2   42       0  101.0  Mild        No
3   31       1   98.0  Mild        No
4   65       1  101.0  Mild        No

In [ ]:
df['cough'] = df['cough'].map({'Mild':0,'Strong':1 })

In [ ]:
x = df.drop(columns = ['has_covid']) ### Input_data or training data
y = df['has_covid'] ### output or testing data

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(
    x,y,test_size=0.2 , random_state= 42
)

In [ ]:
print('total_data_shape' ,df.shape)
print('--------------')
print('total x shape' ,x.shape)
print('x_train shape' ,x_train.shape)
print(' x_test shape' ,x_test.shape)
print('--------------')
print('total y shape' ,y.shape)
print('y_train shape' ,y_train.shape)
print(' y_test shape' ,y_test.shape)

total_data_shape (100, 5)
--------------
total x shape (100, 4)
x_train shape (80, 4)
 x_test shape (20, 4)
--------------
total y shape (100,)
y_train shape (80,)
 y_test shape (20,)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_sc_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [ ]:
np.round(x_train_sc_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean   -0.00   -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01
min    -1.56   -1.19  -1.56  -0.82
25%    -0.94   -1.19  -0.51  -0.82
50%    -0.04    0.84   0.01  -0.82
75%     0.91    0.84   0.53   1.22
max     1.69    0.84   1.57   1.22

In [ ]:
  ############################### On Insurance dataset

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/insurance - insurance.csv')
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
df = df.drop(columns = ['smoker' , 'region'])

In [ ]:
df.head(2)

   age     sex    bmi  children     charges
0   19  female  27.90         0  16884.9240
1   18    male  33.77         1   1725.5523

In [ ]:
df['sex'] = df['sex'].map({'male':1,'female':0})
df.head()

   age  sex     bmi  children      charges
0   19    0  27.900         0  16884.92400
1   18    1  33.770         1   1725.55230
2   28    1  33.000         3   4449.46200
3   33    1  22.705         0  21984.47061
4   32    1  28.880         0   3866.85520

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x = df.drop(columns =['charges'] )
y = df['charges']

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y ,test_size=0.2 ,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_sc_new = pd.DataFrame(x_train_sc ,columns = x_train.columns )

In [ ]:
np.round(x_train_sc_new.describe() ,2)

           age      sex      bmi  children
count  1070.00  1070.00  1070.00   1070.00
mean     -0.00    -0.00    -0.00     -0.00
std       1.00     1.00     1.00      1.00
min      -1.52    -1.02    -2.42     -0.91
25%      -0.88    -1.02    -0.72     -0.91
50%       0.01     0.98    -0.06     -0.09
75%       0.83     0.98     0.65      0.73
max       1.75     0.98     3.74      3.20

In [ ]:
########################### on tips data###############

In [ ]:
df = pd.read_csv('/content/tips - tips.csv')

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
df = df.drop(columns = ['day'])
df = df.drop(columns = ['smoker'])

In [ ]:
df.head()

   total_bill   tip     sex    time  size
0       16.99  1.01  Female  Dinner     2
1       10.34  1.66    Male  Dinner     3
2       21.01  3.50    Male  Dinner     3
3       23.68  3.31    Male  Dinner     2
4       24.59  3.61  Female  Dinner     4

In [ ]:
df['sex'] = df['sex'].map({'Female':1,'Male':0})

In [ ]:
df['time'] = df['time'].map({'Dinner':1,'Lunch':0})

In [ ]:
df.head()

   total_bill   tip  sex  time  size
0       16.99  1.01    1     1     2
1       10.34  1.66    0     1     3
2       21.01  3.50    0     1     3
3       23.68  3.31    0     1     2
4       24.59  3.61    1     1     4

In [ ]:
x = df.drop(columns = ['total_bill'])

In [ ]:
y = df['total_bill']

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_sc_new = pd.DataFrame(x_train_sc ,columns = x_train.columns)

In [ ]:
np.round(x_train_sc_new.describe(), 2)

          tip     sex    time    size
count  195.00  195.00  195.00  195.00
mean    -0.00    0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00
min     -1.46   -0.73   -1.64   -1.68
25%     -0.76   -0.73   -1.64   -0.61
50%     -0.06   -0.73    0.61   -0.61
75%      0.43    1.37    0.61    0.45
max      4.85    1.37    0.61    3.65